# Generated by Django 5.1.1 on 2024-09-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactnum',
            name='con_image',
            field=models.ImageField(blank=True, default=None, max_length=250, null=True, upload_to='images/'),
        ),
    ]
